### ISSUE TITLE
Spelling in activity filter

### ISSUE THREAD

**Issue by richardolsson** [zetkin/www.zetk.in#245]
The Swedish label for the button in the activity filter while inactive is wrong.

**Comment by olleolleolle** [comment]
```yaml
        inactive:
            p: Visar alla aktioner oavsett aktivitet.
            button: Välj aktiviteter att visa aktioner för
```

Are we talking something like this?
